[book]
title = "Shield 游戏服务器框架文档"
description = "Shield 是一个现代化的 C++ 游戏服务器框架，融合了 Pitaya 的分布式架构和 Skynet 的高性能并发模型"
authors = ["cuihairu"]
language = "zh"
multilingual = false
src = "docs"

[build]
build-dir = "book"
create-missing = false
preprocess = ["links", "mermaid"]
use-default-preprocessors = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = []
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
no-section-label = false
git-repository-url = "https://github.com/cuihairu/shield"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/cuihairu/shield/edit/main/docs/{path}"
site-url = "/shield/"
cname = ""
input-404 = ""

[output.html.playground]
copyable = true
copy-js = true
line-numbers = false
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.redirect]

[output.html.fold]
enable = false
level = 0