# Shield Game Server Configuration
# This is the main configuration file for Shield framework

server:
  # Server basic settings
  host: "0.0.0.0"
  port: 8080
  max_connections: 1000
  
  # Actor system configuration
  actor_system:
    node_id: "shield-node-1"
    worker_threads: 4
    scheduler_policy: "sharing"
  
  # Network settings
  network:
    tcp:
      enabled: true
      backlog: 128
      keep_alive: true
    udp:
      enabled: true
      buffer_size: 65536
    websocket:
      enabled: true
      path: "/ws"

# Logging configuration
logger:
  level: "info"  # trace, debug, info, warning, error, fatal
  console_output: true
  log_file: "logs/shield.log"
  max_file_size: 10485760  # 10MB
  max_files: 5
  pattern: "[%Y-%m-%d %H:%M:%S.%f] [%t] [%l] %v"

# Service discovery
discovery:
  type: "local"  # local, etcd, consul, nacos, redis
  
  # Etcd configuration (when type = "etcd")
  etcd:
    endpoints: ["127.0.0.1:2379"]
    
  # Consul configuration (when type = "consul") 
  consul:
    host: "127.0.0.1"
    port: 8500
    
  # Nacos configuration (when type = "nacos")
  nacos:
    server_addr: "127.0.0.1:8848"
    
  # Redis configuration (when type = "redis")
  redis:
    host: "127.0.0.1"
    port: 6379

# Lua script engine
lua:
  enabled: true
  script_path: "scripts"
  vm_pool_size: 8
  max_memory: 67108864  # 64MB per VM

# Monitoring and metrics
metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"

# Game-specific settings
game:
  name: "Shield Game"
  version: "1.0.0"
  max_players: 1000
  tick_rate: 60
  
# Database settings (optional)
database:
  type: "none"  # none, mysql, postgresql, redis
  
  # MySQL configuration (when type = "mysql")
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "shield_game"
    username: "shield"
    password: "password"
    
  # PostgreSQL configuration (when type = "postgresql")  
  postgresql:
    host: "127.0.0.1"
    port: 5432
    database: "shield_game"
    username: "shield"
    password: "password"
