#define BOOST_TEST_MODULE ActorSystemConfigTest
#include <boost/test/unit_test.hpp>
#include <stdexcept>

#include "shield/actor/actor_system_config.hpp"

using namespace shield::actor;

BOOST_AUTO_TEST_SUITE(ActorSystemConfigTests)

BOOST_AUTO_TEST_CASE(TestDefaultValues) {
    ActorSystemConfig config;
    BOOST_CHECK_EQUAL(config.node.node_id, "shield-node-1");
    BOOST_CHECK_EQUAL(config.node.cluster_name, "shield-cluster");
    BOOST_CHECK(config.node.auto_generate_node_id);
    BOOST_CHECK_EQUAL(config.scheduler.policy, "sharing");
    BOOST_CHECK_EQUAL(config.scheduler.max_throughput, 300);
    BOOST_CHECK(config.network.enabled);
    BOOST_CHECK_EQUAL(config.network.host, "0.0.0.0");
    BOOST_CHECK(config.monitor.enable_metrics);
    BOOST_CHECK_EQUAL(config.monitor.metrics_interval, 5000);
    BOOST_CHECK(config.memory.enable_gc);
    BOOST_CHECK_EQUAL(config.memory.max_memory_per_actor, 67108864u);
}

BOOST_AUTO_TEST_CASE(TestPropertiesName) {
    ActorSystemConfig config;
    BOOST_CHECK_EQUAL(config.properties_name(), "actor_system");
}

BOOST_AUTO_TEST_CASE(TestSupportsHotReload) {
    ActorSystemConfig config;
    BOOST_CHECK(config.supports_hot_reload());
}

BOOST_AUTO_TEST_CASE(TestValidateValid) {
    ActorSystemConfig config;
    BOOST_CHECK_NO_THROW(config.validate());
}

BOOST_AUTO_TEST_CASE(TestValidateEmptyNodeIdWithNoAutoGenerate) {
    ActorSystemConfig config;
    config.node.node_id = "";
    config.node.auto_generate_node_id = false;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateEmptyNodeIdWithAutoGenerate) {
    ActorSystemConfig config;
    config.node.node_id = "";
    config.node.auto_generate_node_id = true;
    BOOST_CHECK_NO_THROW(config.validate());
}

BOOST_AUTO_TEST_CASE(TestValidateEmptyClusterName) {
    ActorSystemConfig config;
    config.node.cluster_name = "";
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateInvalidSchedulerPolicy) {
    ActorSystemConfig config;
    config.scheduler.policy = "invalid";
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateValidSchedulerPolicies) {
    ActorSystemConfig config;
    config.scheduler.policy = "sharing";
    BOOST_CHECK_NO_THROW(config.validate());
    config.scheduler.policy = "stealing";
    BOOST_CHECK_NO_THROW(config.validate());
}

BOOST_AUTO_TEST_CASE(TestValidateZeroThroughput) {
    ActorSystemConfig config;
    config.scheduler.max_throughput = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateNetworkEmptyHost) {
    ActorSystemConfig config;
    config.network.enabled = true;
    config.network.host = "";
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateNetworkZeroMaxConnections) {
    ActorSystemConfig config;
    config.network.enabled = true;
    config.network.max_connections = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateNetworkZeroTimeout) {
    ActorSystemConfig config;
    config.network.enabled = true;
    config.network.connection_timeout = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateDisabledNetworkSkipsChecks) {
    ActorSystemConfig config;
    config.network.enabled = false;
    config.network.host = "";
    config.network.max_connections = 0;
    BOOST_CHECK_NO_THROW(config.validate());
}

BOOST_AUTO_TEST_CASE(TestValidateZeroMetricsInterval) {
    ActorSystemConfig config;
    config.monitor.metrics_interval = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateZeroMaxMemory) {
    ActorSystemConfig config;
    config.memory.max_memory_per_actor = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestValidateZeroMessageBuffer) {
    ActorSystemConfig config;
    config.memory.message_buffer_size = 0;
    BOOST_CHECK_THROW(config.validate(), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(TestGetEffectiveWorkerThreads) {
    ActorSystemConfig config;
    config.scheduler.worker_threads = 4;
    BOOST_CHECK_EQUAL(config.get_effective_worker_threads(), 4);

    config.scheduler.worker_threads = 0;
    BOOST_CHECK_GT(config.get_effective_worker_threads(), 0);
}

BOOST_AUTO_TEST_CASE(TestGetEffectiveNodeIdExplicit) {
    ActorSystemConfig config;
    config.node.auto_generate_node_id = false;
    config.node.node_id = "my-node";
    BOOST_CHECK_EQUAL(config.get_effective_node_id(), "my-node");
}

BOOST_AUTO_TEST_CASE(TestGetEffectiveNodeIdAutoGenerated) {
    ActorSystemConfig config;
    config.node.auto_generate_node_id = true;
    config.node.node_id = "";
    auto id = config.get_effective_node_id();
    BOOST_CHECK(!id.empty());
    // Should contain hostname_pid_timestamp format
    BOOST_CHECK(id.find('_') != std::string::npos);
}

BOOST_AUTO_TEST_CASE(TestFromPtree) {
    boost::property_tree::ptree pt;
    pt.put("node.node_id", "custom-node");
    pt.put("node.cluster_name", "custom-cluster");
    pt.put("scheduler.policy", "stealing");
    pt.put("scheduler.worker_threads", 8);
    pt.put("scheduler.max_throughput", 500);
    pt.put("network.enabled", false);
    pt.put("monitor.metrics_interval", 10000);
    pt.put("memory.max_memory_per_actor", 134217728);

    ActorSystemConfig config;
    config.from_ptree(pt);

    BOOST_CHECK_EQUAL(config.node.node_id, "custom-node");
    BOOST_CHECK_EQUAL(config.node.cluster_name, "custom-cluster");
    BOOST_CHECK_EQUAL(config.scheduler.policy, "stealing");
    BOOST_CHECK_EQUAL(config.scheduler.worker_threads, 8);
    BOOST_CHECK_EQUAL(config.scheduler.max_throughput, 500);
    BOOST_CHECK(!config.network.enabled);
    BOOST_CHECK_EQUAL(config.monitor.metrics_interval, 10000);
    BOOST_CHECK_EQUAL(config.memory.max_memory_per_actor, 134217728u);
}

BOOST_AUTO_TEST_SUITE_END()
