// Covers the runtime-callable helpers generated by CAF_ADD_ATOM in
// shield/core/service_message.hpp: the equality operators and the inspect()
// overload used by CAF inspectors. These inline definitions are never called
// by the service actors themselves (the atoms travel as unsafe message
// types), so this suite exercises them directly.
#define BOOST_TEST_MODULE ServiceMessageTypesTests
#include <boost/test/unit_test.hpp>

#include "shield/core/service_message.hpp"

using namespace shield::lua;

namespace {

// Minimal stand-in for a CAF inspector: CAF_ADD_ATOM generates an inspect()
// overload whose body only calls f.object(x).fields(); a type exposing
// exactly that surface is enough to exercise the overload at runtime.
struct RecordingInspector {
    template <class T>
    struct ObjectHandle {
        bool fields() const { return true; }
    };

    template <class T>
    ObjectHandle<T> object(T&) {
        return {};
    }
};

template <class Atom>
void exercise_atom(const Atom& a, const Atom& b) {
    // operator== / operator!= generated by CAF_ADD_ATOM_3.
    BOOST_CHECK(a == b);
    BOOST_CHECK(!(a != b));

    // inspect() overload generated by CAF_ADD_ATOM_3.
    Atom mutable_a{};
    RecordingInspector inspector;
    BOOST_CHECK(inspect(inspector, mutable_a));
}

}  // namespace

BOOST_AUTO_TEST_SUITE(ServiceMessageTypesTests)

BOOST_AUTO_TEST_CASE(AtomEqualityOperatorsHoldForAllTagTypes) {
    exercise_atom(timer_fire_atom{}, timer_fire_atom{});
    exercise_atom(call_timeout_atom{}, call_timeout_atom{});
    exercise_atom(init_ready_atom{}, init_ready_atom{});
    exercise_atom(fork_task_atom{}, fork_task_atom{});
}

BOOST_AUTO_TEST_CASE(MessageStructsRoundTripDefaultFields) {
    // Sanity-check the payload structs' default field values; the CAF type
    // IDs above are what make pattern matching on them type-safe.
    ServiceMessage msg;
    BOOST_CHECK_EQUAL(msg.deadline_ms, 0);
    BOOST_CHECK_EQUAL(msg.call_session, 0u);
    BOOST_CHECK_EQUAL(msg.session_id, 0u);
    BOOST_CHECK_EQUAL(msg.session_epoch, 0u);
    BOOST_CHECK(msg.priority == MessagePriority::Normal);
    BOOST_CHECK(msg.args.is_null());

    SyncCallMessage sync;
    BOOST_CHECK_EQUAL(sync.sync_session, 0u);
    BOOST_CHECK(sync.args.is_null());

    CallResponseMessage resp;
    BOOST_CHECK(!resp.ok);
    BOOST_CHECK(resp.values.is_array());
    BOOST_CHECK(resp.values.empty());
}

BOOST_AUTO_TEST_SUITE_END()
